version: '3'

services:

  ##### Weviate VECTOR SEARCH ENGINE #####
  weaviate:
    container_name: ds_weaviate
    image: semitechnologies/weaviate:1.17.3
    restart: always
    ports:
    - 8080:8080
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ds_weviate_data:/var/lib/weaviate

  ##### Nuxt FRONTEND APPLICATION #####
  node:
    container_name: node
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    restart: always
    ports:
      - 3010:3010
    expose:
      - 3010
    environment:
      PORT: 3010
      HOST: 0.0.0.0
    volumes:
      - ./frontend:/app

volumes:
  ds_weviate_data: