version: '3'

services:

  ##### Weviate VECTOR SEARCH ENGINE #####
  weaviate:
    container_name: ds_weaviate
    image: semitechnologies/weaviate:1.17.3
    restart: always
    ports:
    - 8080:8080
    env_file:
      - .env
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ds_weviate_data:/var/lib/weaviate

  ##### Camunda ROBOTIC PROCESS AUTOMATION #####
  automation:
    container_name: ds-automation
    build:
      context: ./
      dockerfile: ./docker/automation/Dockerfile
    restart: always
    ports:
      - 3200:3200
    expose:
      - '3200'
    env_file:
      - .env

volumes:
  ds_weviate_data: